const Map<String, String> enUS = {
  "app_tittle": "Wahat Al Shifa",
  "login_txt_welcom": "Welcome to Wahat Al Shifa",
  "welcome": "Welcome",
  "txtLangSelection":
      "Please select your language for easy\nusage of your complete Process",
  "setLang": "Set your Language",
  "continue": "Continue",
  "auth_account_details": "Account Details",
  "auth_account_verification": "Account Verification",
  "auth_enter_otp": "Enter OTP",
  "auth_resend_otp": "Resend OTP",
  "auth_change_mobile_number": "Change Mobile number",
  "auth_phone_number": "Phone Number",
  "auth_nationality_id": "Nationality ID",
  "auth_select_nationality_id": "Select Nationality Type",
  "auth_nationality_type": "Nationality ID Type",
  "auth_patient_login": "Patient Login",
  "auth_email_address": "Email Address",
  "auth_gender": "Gender",
  "auth_select": "Select",
  "auth_dob": "Date of Birth",
  "auth_full_name": "Full Name",
  "auth_add_details_reg": "Add Details for Registration",
  "auth_verify_details": "Verify Details",
  "auth_registered_success": "Patient registered Successfully",
  "auth_please_enter_nationality_id": "Please enter Nationality ID",
  "auth_please_select_nationality_id_type": "Please select Nationality ID type",
  "auth_lease_enter_phone_number": "Please enter Phone Number",
  "auth_please_enter_exactly_10_digits": "Please enter exactly 10 digits",
  "auth_select_branch": "Select Branch",
  "auth_choose_your_branch": "Choose your Branch",
  "auth_please_select_branch": "Please Select Branch",

  "btm_menu_home": "Home",
  "btm_menu_appoinment": "Appoinment",
  "btm_menu_patient_record": "Patient record",
  "btm_menu_profile": "Profile",
  "internet_not_available": "Internet not available",
  "reload": "Reload",
  "go_settings": "Go settings",

  //home page
  "home_Search_Department_and_specialities": "Search Department & Specialities",
  "home_take_doctor_appointment": "Take Doctor appointment",
  "home_take_doctor_appointment_desc": "Choose from our top doctors available",
  "home_view_all": "View All",
  "home_SAR_250": "SAR 250",
  "home_wallet_balance": "Wallet Balance",
  "home_get_exclusive": "Get Exclusive",
  "home_all_offers": "All Offers",

  //notification = notify
  "notify_txt": "Notification",
  "notify_clear_all": "Clear All",
  "notify_notification_tile": "Notification Tile",
  "notify_cleared_successfully": "Notifications Cleared successfully",

  //Specialities
  "spclties_txt": "Specialities",
  "spclties_srch_spclties_and_dept": "Search Specialities, Department",

  //Doctor list view
  "doc_list_search_doc": "Search doctor",
  "doc_list_hsptl_name": "Alshifa hospital, Riyad",
  "doc_list_next_available": "Next Available",
  "doc_list_consultation_fee": "Consultation Fee ",
  "doc_list_book_hsptl_visit": "Book Hospital Visit",

  //Book Hospital Visit
  "doc_slots_book_hsptl_visit": "Book Hospital Visit",
  "doc_slots_consultation_fee": "Consultation Fee",
  "doc_slots_hsptl_name": "Alshifa hospital",
  "doc_slots_hsptl_address": "Exit 14, Ar Rabwah District, Riyadh",
  "doc_slots_Schedule": "Schedule",
  "doc_slots_about_doc": "About Doctor",
  "doc_slots_reviews": "Reviews",
  "doc_slots_morning": "Morning",
  "doc_slots_evening": "Evening",
  "doc_slots_night": "Night",
  "doc_slots_select_slot_to_book_appointment":
      "Select a slot to book appointment",
  "doc_slots_book_appointment": "Book Appointment",

  //About Doctor
  "about_doc_bio": "Biography",
  "about_doc_qualification": "Qualificaton",
  "about_doc_avilability": "Availability",
  "about_doc_day": "Day",
  "about_doc_avilable_hours": "Avilable Hours",

  //select patient bottomsheet
  "btm_select_patient_txt": "Select Patient",
  "btm_select_patient_add_member": "Add Member",
  "btm_select_patient_DOB": "DOB",
  "btm_select_patient_confirm_patient": "Confirm Patient",

  //Add family member
  "add_fam_mem_txt": "Add Family member",
  "add_fam_mem_first_name": "First Name",
  "add_fam_mem_enter_your_first_name": "Enter your First Name",
  "add_fam_mem_second_name": "Second Name",
  "add_fam_mem_enter_your_second_name": "Enter your Second Name",
  "add_fam_mem_nationality_ID_type": "Nationality ID Type",
  "add_fam_mem__please_select_a_nationality_ID_type":
      "Please select a nationality ID type",
  "add_fam_mem_ID_number": "ID Number",
  "add_fam_mem_enter_your_ID_number": "Enter your ID Number",
  "add_fam_mem_dob": "Date of Birth",
  "add_fam_mem_DD-MM-YYYY": "DD-MM-YYYY",
  "add_fam_mem_enter_your_dob": "Enter your Date of Birth",
  "add_fam_mem_select_relation": "select",
  "add_fam_mem_relation": "Relation",
  "add_fam_mem_please_select_a_relation": "Please select a Relation",
  "add_fam_mem_add_fam_mem_select_gender": "Select",
  "add_fam_mem_gender": "Gender",
  "add_fam_mem_male": "male",
  "add_fam_mem_female": "female",
  "add_fam_mem_please_select_a_gender": "Please select a Gender",
  "add_fam_mem_mob_num": " Mobile Number",
  "add_fam_mem_enter_your_mob_num": "Enter your Mobile Number",
  "add_fam_mem_cancel": "Cancel",
  "add_fam_mem_save": "Save",
  "add_fam_mem_fam_mem_added_successfully": "Family member added successfully",
  "add_fam_select_gender": "Please select a Gender",
  "add_fam_edit_success": "family member relation edited successfully",

  //Review and Pay
  "review_and_pay_txt": "Review & Pay",
  "review_and_pay_appointment_details": "Appointment Details",
  "review_and_pay_hsptl_name": "Alshifa hospital",
  "review_and_pay_hsptl_address": "Exit 14, Ar Rabwah District, Riyadh",
  "review_and_pay_selected_patient": "Selected Patient",
  "review_and_pay_cancel_and_reschudule": "Cancelation and Reschudule",
  "review_and_pay_read_cancellation_reschdule_policy":
      "Read Cancellation & Reschdule policy",
  "review_and_pay_total_bill": "Total Bill",
  "review_and_pay_consultation_fee": "Consultation Fee",
  "review_and_pay_vat": "VAT",
  "review_and_pay_total_paid": "Total Paid",
  "review_and_pay_pay_txt": "Pay",
  "review_and_pay_confirm_appmnt": "Confirm Appointment",
  //Cancellation and Reschdule policy = c_r policy
  "c_r_policy_txt": "Cancelation and Reschedule Policy",
  "c_r_policy_cancellation_policy": "Cancellation Policy",
  "c_r_cancellation_policy_txt":
      "Patients may cancel appointments up to 24 hours before the scheduled time through the mobile app. As you are our valued patient, the full amount will be refunded to your in-app wallet and can be used for future bookings.If the cancellation is due to unforeseen circumstances, we will gladly assist in rescheduling at the next available time. We highly appreciate receiving at least 8 hours’ notice, as each appointment slot is exclusively reserved. Frequent or unnecessary cancellations may affect scheduling efficiency and service availability for others.",
  "c_r_policy_reschedule_policy": "Reschedule Policy",
  "c_r_reschedule_policy_txt":
      "Appointments can be rescheduled up to 24 hours before the original appointment time through the mobile app. If cancellation is required, the full amount will be refunded to your in-app wallet as a valued patient and can be reused for future bookings.In case of unforeseen situations, we will do our best to accommodate you at the next available time. Early notice is appreciated to help maintain smooth operations for all patients.",
  "c_r_policy_close": "Close",

  //Bill total
  "bill_total_txt": "Bill Total :",
  "bill_total_hsptl_name": "Alshifa hospital, Riyad",
  "bill_total_apply_coupon": "Apply Coupon",
  "bill_total_apply": "Apply",
  "bill_total_enter_code": "Enter Code",
  "bill_total_total_bill": "Total Bill",
  "bill_total_consultation_fee": "Consultation Fee",
  "bill_total_VAT": "VAT",
  "bill_total_total_paid": "Total Paid",
  "bill_total_wallet_balance": "Wallet Balance : ",
  "bill_total_credit/debit_cards": "Credit/Debit Cards",
  "bill_total_add_new_card": "Add New Card",
  "bill_total_save_and_pay_via_card": "Save and Pay via Card",
  "bill_total_more_payment_options": "More Payment Options",
  "bill_total_pay_at_hospital": "Pay At Hospital",
  "bill_total_pay_in_cash_at_hsptl": "Pay in cash or Card at alshifa hospital",
  "bill_total_swipe_to_pay": "Swipe to Pay",
  "bill_total_payment_processing": "Payment Processing...",
  "bill_total_coupon_amount": "Coupon Amount",

  //Booking confirmation
  "booking_confirm_Share": "Share",
  "booking_confirm_hsptl_name": "Alshifa hospital, Riyad",
  "booking_confirm_booking_confirmed": "Booking Confirmed",
  "booking_confirm_get_direction": "Get direction",
  "booking_confirm_15_min_before_your_slot":
      "Reach the Hospital 15 mins before your slot",
  "booking_confirm_selected_patient": "Selected Patient",
  "booking_confirm_total_bill": "Total Bill",
  "booking_confirm_consultation_fee": "Consultation Fee",
  "booking_confirm_VAT": "VAT",
  "booking_confirm_total_paid": "Total Paid",
  "booking_confirm_view_appointment": "View Appointment",
  "booking_confirm_home": "Home",

  //wallet balance
  "wallet_txt": "Wallet",
  "wallet_add_balance": "Add balance",
  "wallet_your_wallet": "Your Wallet",
  "wallet_balance": "Balance",
  "wallet_SAR": "SAR",
  "wallet_transaction_log": "Wallet Transaction Log",

  //Add money to wallet
  "money_wallet_txt": "Add money to Wallet",
  "money_wallet_balance": "Wallet Balance",
  "money_wallet_add_money": "Add money to Wallet",
  "money_wallet_enter_money": "Enter your Wallet Amount",
  "money_wallet_add": "Add Money",
  "money_wallet_added_success": "Added money successfully",

  //offers list
  "offer_list_txt": "Offer List",
  "offer_valid_date": "Offer Valid",
  "offer_details_txt": "Offer Details",
  "offer_coupon_code": "Coupon Code",
  "offer_copy_coupon_code": "Copy Code",
  "offer_coupon_code_copied": "Coupon code copied!",
  "offer_valid_upto": "Offer Valid Upto",
  "offer_T_and_C": "Terms and Condition",
  "offer_book_now": "Book Now",

  //appoinment page = appmnt
  "appmnt_all_patient": "All Patient",
  "appmnt_select_patient": "Select Patient",
  "appmnt_active_appointments": "Active Appointments",
  "appmnt_hospital_name": "Wahat alshifa medical complex",
  "appmnt_reschedule": "Reschedule",
  "appmnt_cancel_appointment": "Cancel Appointment",
  "appmnt_rate_this_service_now": "Rate this Service now",
  "appmnt_cmplt_cncl_appmnt": "Completed/Cancelled Appointments",
  "appmnt_book_flwup_now": "Book Followup Visit",

  //cancel appoinment
  "cancel_appmnt_txt": "Cancel Appointment",
  "cancel_appmnt_r_u_sure_cancel": "Are you Sure Cancel Appointment ?",
  "cancel_appmnt_read_policy": "Read Cancellation Policy",
  "cancel_appmnt_policy": "Cancelation Policy",
  "cancel_appmnt_no": "No",
  "cancel_appmnt_yes": "Yes",

  //appointment cancled
  "appmnt_cancled_txt": "Appointment Cancelled",
  "appmnt_cancled_successfully": "Successfully",
  "appmnt_cancled_Close": "Close",

  //Reschedule
  "reschedule_txt": "Reschedule Appointment",
  "reschedule_r_u_sure_cancel": "Are you Sure Reschedule Appointment?",
  "reschedule_read_policy": "Read Reschedule Policy",
  "reschedule_policy": "Reschedule Policy",

  //book follow up
  "book_flw_up_txt": "Book Follow up",
  "book_flw_up_appmnt_id": "Appointment ID",
  "book_flw_up_eligible_flw_up_until": "Eligible Followup Until : ",
  "book_flw_up_txt_book_flw_up_visit": "Book Followup Visit",

  //star rating
  "rating_rate_this_appmnt": "Rate this Apointment",
  "rating_Helpful": "Helpful",
  "rating_Understanding": "Understanding",
  "rating_Consultation": "Consultation",
  "rating_communication": "communication",
  "rating_Behaviour": "Behaviour",
  "rating_Handling": "Handling",
  "rating_Write_review": "Write your review (optional)",
  "rating_submit": "Submit",
  "rating_close": "Close",

  //patient record
  "patient_rec_your_health_record": "Your health record",

  //EMR
  "patient_rec_patient_EMR": "EMR",
  "patient_rec_patient_EMR_history": "Patient EMR History",
  "patient_rec_emr_list_all_patient": "All Patient",
  "patient_rec_emr_list_complaint": "Complaint",
  "patient_rec_emr_list_reports": "Reports",
  "patient_rec_emr_list_select_patient": "Select Patient",
  "patient_rec_emr_view_patient_EMR_history": "Patient EMR History",
  "patient_rec_emr_view_dob": "DOB",
  "patient_rec_emr_view_gender": "Gender",
  "patient_rec_emr_view_complaint": "Complaint",
  "patient_rec_emr_view_treatment": "Treatment",
  "patient_rec_emr_view_significant_signs": "Significant signs",
  "patient_rec_emr_view_vitals": "Vitals",
  "patient_rec_emr_view_illness_types": "Illness Types",
  "patient_rec_emr_view_status": "Status",
  "patient_rec_emr_view_diagnosis": "Diagnosis",
  "patient_rec_emr_view_view_reports": "View Reports",
  "patient_rec_emr_view_search_mem": "Search Member",

  //Lab report
  "patient_rec_lab_report": "Lab Report",
  "patient_rec_lab_patient_lab_report": "Patient Lab Report",
  "patient_rec_lab_rep_list_all_patient": "All Patient",
  "patient_rec_lab_rep_list_select_patient": "Select Patient",
  "patient_rec_lab_rep_list_result_by": "Result By",
  "patient_rec_lab_rep_list_status": "Status",
  "patient_rec_lab_rep_list_reports": "Reports",
  "patient_rec_lab_rep_view": "Patient Lab Report View",
  "patient_rec_lab_rep_view_order_num": "Order Number",
  "patient_rec_lab_rep_view_payer": "Payer",
  "patient_rec_lab_rep_view_collection_by": "Collection By",
  "patient_rec_lab_rep_view_collection_date": "Collection Date",
  "patient_rec_lab_rep_view_result_by": "Result By",
  "patient_rec_lab_rep_view_result_date": "Result Date",
  "patient_rec_lab_rep_view_status": "Status",
  "patient_rec_lab_rep_view_result_remarks": "Result Remarks",
  "patient_rec_lab_rep_view_view_reports": "View Reports",
  "patient_rec_lab_rep_view_search_mem": "Search Member",

  //Procedure Details = proc
  "patient_rec_proc": "Procedure",
  "patient_rec_proc_details": "Procedure Details",
  "patient_rec_proc_list_all_patient": "All Patient",
  "patient_rec_proc_list_select_patient": "Select Patient",
  "patient_rec_proc_list_process_date": "Process Date",
  "patient_rec_proc_list_status": "Status",
  "patient_rec_proc_list_reports": "Reports",
  "patient_rec_proc_view_procedure_details_view": "Procedure Details View",
  "patient_rec_proc_view_order_num": "Order Number",
  "patient_rec_proc_view_payer": "Payer",
  "patient_rec_proc_view_item": "Item",
  "patient_rec_proc_view_rocess_by": "Process By",
  "patient_rec_proc_view_process_date": "Process Date",
  "patient_rec_proc_view_status": "Status",
  "patient_rec_proc_view_remarks": "Remarks",
  "patient_rec_proc_view_view_rep": "View Reports",
  "patient_rec_proc_view_search_mem": "Search Member",

  //Prescription Details = presc
  "patient_rec_presc": "Prescription",
  "patient_rec_presc_details": "Prescription Details",
  "patient_rec_presc_list_all_patient": "All Patient",
  "patient_rec_presc_list_select_patient": "Select Patient",
  "patient_rec_presc_list_name": "Name",
  "patient_rec_presc_list_status": "Status",
  "patient_rec_presc_list_view_prescription": "View Prescription",
  "patient_rec_presc_details_view": "Prescription details View",
  "patient_rec_presc_view_code": "Code",
  "patient_rec_presc_view_payer": "Payer",
  "patient_rec_presc_view_name": "Name",
  "patient_rec_presc_view_gen_name": "Generic Name",
  "patient_rec_presc_view_order_QTY": "Order QTY",
  "patient_rec_presc_view_dispense_QTY": "Dispense QTY",
  "patient_rec_presc_view_status": "Status",
  "patient_rec_presc_view_instruction": "Instruction",
  "patient_rec_presc_view_presc": "View Prescription",
  "patient_rec_presc_view_search_mem": "Search Member",

  //Radiology = rad
  "patient_rec_rad": "Radiology",
  "patient_rec_rad_details": "Radiology Details",
  "patient_rec_rad_list_all_patient": "All Patient",
  "patient_rec_rad_list_select_patient": "Select Patient",
  "patient_rec_rad_list_process_date": "Process Date",
  "patient_rec_rad_list_status": "Status",
  "patient_rec_rad_list_reports": "Reports",
  "patient_rec_rad_details_view": "Radiology Details View",
  "patient_rec_rad_view_order_num": "Order Number",
  "patient_rec_rad_view_payer": "Payer",
  "patient_rec_rad_view_item": "Item",
  "patient_rec_rad_view_process_by": "Process By",
  "patient_rec_rad_view_processdate": "Process Date",
  "patient_rec_rad_view_status": "Status",
  "patient_rec_rad_view_remarks": "Remarks",
  "patient_rec_rad_view_view_rep": "View Reports",
  "patient_rec_rad_view_search_mem": "Search Member",

  //sick leave
  "patient_rec_sick_leave": "Sick Leave",
  "patient_rec_sick_leave_letters": "Sick leave letters",
  "patient_rec_sick_list_all_patient": "All Patient",
  "patient_rec_sick_list_select_patient": "Select Patient",
  "patient_rec_sick_list_created_by": "Created By",
  "patient_rec_sick_list_sick_leave_days": "Sick Leave Days",
  "patient_rec_sick_list_view_letter": "View Letter",
  "patient_rec_sick_leave_letters_view": "Sick leave letters View",
  "patient_rec_sick_view_leave_num": "Sick Leave Number",
  "patient_rec_sick_view_leave_days": "Sick Leave Days",
  "patient_rec_sick_view_created_by": "Created By",
  "patient_rec_sick_view_remarks": "Remarks",
  "patient_rec_sick_view_view_letter": "View Letter",
  "patient_rec_sick_view_search_mem": "Search Member",

  //Medical Report = med rep
  "patient_rec_med_rep": "Medical Report",
  "patient_rec_med_rep_list_all_patient": "All Patient",
  "patient_rec_med_rep_list_select_patient": "Select Patient",
  "patient_rec_med_rep_list_created_by": "Created by",
  "patient_rec_med_rep_list_rep_num": "Report number",
  "patient_rec_med_rep_list_reports": "Reports",
  "patient_rec_med_rep_view": "Medical Report View",
  "patient_rec_med_rep_view_med_rep_num": "Medical Report Number",
  "patient_rec_med_rep_view_created_by": "Created By",
  "patient_rec_med_rep_view_remarks": "Remarks",
  "patient_rec_med_rep_view_Rep": "View Reports",
  "patient_rec_med_rep_view_search_mem": "Search Member",

  //Profile page = prof
  "prof_view_acc_details": "View Account Details",
  "prof_patient_list": "Patient List",
  "prof_my_reviews": "My Reviews",
  "prof_notification_settings": "Notification Settings",
  "prof_change_language": "Change Language",
  "prof_privacy_policy": "Privacy policy",
  "prof_log_out": "Log Out",

  //View Account Details
  "prof_acc_details": "Account Details",
  "prof_acc_details_full_name": "Full Name",
  "prof_acc_details_nationality": "Nationality",
  "prof_acc_details_nationality_id": "Nationality ID",
  "prof_acc_details_dob": "Date Of Birth",
  "prof_acc_details_gender": "Gender",
  "prof_acc_details_email": "Email Address",
  "prof_acc_details_prof_pic": "Profile picture",
  "prof_acc_details_log_out": "Log Out",

  //patient list
  "prof_pati_list_fam_mem": "Family Member",
  "prof_pati_add_member": "Add Member",

  //add family member
  "prof_add_fam_mem_txt": "Add Member",
  "prof_add_fam_mem_fam_mem": "Family Member",
  "prof_add_fam_mem": "Add Family Member",
  "prof_add_fam_mem_full_name": "Full Name",
  "prof_add_fam_mem_enter_your_first_name": "Enter your First Name",
  "prof_add_fam_mem_nationality_ID_type": "Nationality ID Type",
  "prof_add_fam_mem_please_select_a_nationality_ID_type":
      "Please select a nationality ID type",
  "prof_add_fam_mem_enter_your_ID_number": "Enter your ID Number",
  "prof_add_fam_mem_ID_number": "ID Number",
  "prof_add_fam_mem_dob": "Date of Birth",
  "prof_add_fam_mem_enter_your_dob": "Enter your Date of Birth",
  "prof_add_fam_mem_DD_MM_YYYY": "DD-MM-YYYY",
  "prof_add_fam_mem_relation": "Relation",
  "prof_add_fam_mem_select_relation": "Select",
  "prof_add_fam_mem_please_select_a_relation": "Please select a Relation",
  "prof_add_fam_mem_gender": "Gender",
  "prof_add_fam_mem_please_select_a_gender": "Please select a Gender",
  "prof_add_fam_mem_select_gender": "Select",
  "prof_add_fam_mem_mobile_num": "Mobile Number",
  "prof_add_fam_mem_enter_your_mobile_num": "Enter your Mobile Number",
  "prof_add_fam_mem_edit_details": "Edit Details",

  //my reviews
  "prof_my_review": "Reviews",

  //Notification Settings
  "prof_notification_settings_appbar": "Notification Settings",
  "prof_notify_settings_enable_appmnt_reminder": "Enable appointment Reminder",
  "prof_notify_settings_medical_record_update": "Medical Record Update",
  "prof_notify_settings_health_alerts": "Health Alerts",
  "prof_notify_settings_set_custom_reminder_time": "Set Custom Reminder Time",
  "prof_notify_settings_one_day_before": "One Day before",
  "prof_notify_settings_save_preference": "Save Preference",

  //change language
  "prof_chng_lang_set_lang": "Set Language",
  "prof_chng_lang_arabic_lang": "عربي",
  "prof_chng_lang_english_lang": "English",
  "prof_chng_lang_save_preference": "Save Preference",

  //Privacy policy
  "prof_privacy_policy_appbar": "Privacy Policy",
  "prof_privacy_policy_txt": "Privacy Policy",
  "prof_terms_and_conditions_txt": "Terms and Condition",
  "hsptl_privacy_policy":
      "At Wahat Al Shifa Medical Complex, we are committed to protecting your privacy. All personal information collected through our mobile app, including your name, contact details, health records, and appointment history, is stored securely and used only for medical and service-related purposes.We strictly adhere to applicable data protection laws in the Kingdom of Saudi Arabia. Your data will never be shared with third parties without your explicit consent, except where required by law or for essential medical coordination.By using our app, you consent to the collection and use of your information in accordance with this policy. You may update or request removal of your data at any time by contacting our support team.",

  //Log out
  "log_out_txt": "Log Out",

  "cons_no_data": "Something went wrong Please try again later",
  "cons_no_data_body": "No doctors available at the moment",
  "cons_doctor_not_avilable": "Doctor not available",
  "cons_patient_not_avilable": "Patient not available",
  "somthing_wrng_try_again": "Something went wrong. Please try again.",

  //
  "registration_num": "Registration Number",
  "reg_age": "Age",
  "select_options": "Select options",
  "enter_ur_age": "Enter your Age",
  "enter_ur_reg_num": "Enter your Registration number",
  "lang_chnge_success": "تم تغيير اللغة بنجاح",
  "coupon_success_msg": "Coupon applied successfully",
  "booked_success": "Booked successfully",
  "star_rating_success": "Star Rating Saved successfully",
  "age": "Age",
  "year": "Years",
  "free": "Free",
  "added money successfully": "Added money successfully",
  "rescheduled successfully": "Rescheduled Successfully",
  "image deleted successfully": "Image deleted successfully",
  "image uploaded successfully!": "Image uploaded successfully!"
};
