const Map<String, String> arSA = {
  "app_tittle": "واحة الشفاء",
  "login_txt_welcom": "مرحبًا بكم في واحة الشفاء",
  "welcome": "مرحبًا",
  "txtLangSelection": "يرجى اختيار لغتك لتسهيل استخدامك لكامل الإجراءات",
  "setLang": "اختر لغتك",
  "continue": "استمرار",
  "auth_account_details": "تفاصيل الحساب",
  "auth_account_verification": "التحقق من الحساب",
  "auth_enter_otp": "أدخل رمز التحقق (OTP)",
  "auth_resend_otp": "إعادة إرسال رمز التحقق",
  "auth_change_mobile_number": "تغيير رقم الجوال",
  "auth_phone_number": "رقم الجوال",
  "auth_nationality_id": "رقم الهوية الوطنية",
  "auth_select_nationality_id": "اختر نوع الجنسية",
  "auth_nationality_type": "نوع الجنسية",
  "auth_patient_login": "تسجيل دخول المريض",
  "auth_email_address": "البريد الإلكتروني",
  "auth_gender": "الجنس",
  "auth_select": "اختر",
  "auth_dob": "تاريخ الميلاد",
  "auth_full_name": "الاسم الكامل",
  "auth_add_details_reg": "أضف التفاصيل للتسجيل",
  "auth_verify_details": "تحقق من التفاصيل",
  "auth_registered_success": "تم تسجيل المريض بنجاح",
  "auth_please_enter_nationality_id": "يرجى إدخال رقم الهوية الوطنية",
  "auth_please_select_nationality_id_type": "يرجى اختيار نوع هوية الجنسية",
  "auth_lease_enter_phone_number": "يرجى إدخال رقم الهاتف",
  "auth_please_enter_exactly_10_digits": "يرجى إدخال 10 أرقام بالضبط",
  "auth_select_branch": "اختر الفرع",
  "auth_choose_your_branch": "اختر فرعك",
  "auth_please_select_branch": "يرجى اختيار الفرع",

  "btm_menu_home": "الرئيسية",
  "btm_menu_appoinment": "الموعد",
  "btm_menu_patient_record": "سجل المريض",
  "btm_menu_profile": "الملف الشخصي",
  "internet_not_available": "الإنترنت غير متوفر",
  "reload": "إعادة التحميل",
  "go_settings": "اذهب إلى الإعدادات",

  //home page
  "home_Search_Department_and_specialities": "ابحث عن القسم والتخصصات",
  "home_take_doctor_appointment": "احجز موعدًا مع طبيب",
  "home_take_doctor_appointment_desc": "اختر من بين أفضل الأطباء المتاحين",
  "home_view_all": "عرض الكل",
  "home_SAR_250": "ريال سعودي",
  "home_wallet_balance": "رصيد المحفظة",
  "home_get_exclusive": "احصل على عروض حصرية",
  "home_all_offers": "جميع العروض",

  //notification = notify
  "notify_txt": "الإشعارات",
  "notify_clear_all": "مسح الكل",
  "notify_notification_tile": "عنوان الإشعار",
  "notify_cleared_successfully": "تم مسح الإشعارات بنجاح",

  //Specialities
  "spclties_txt": "التخصصات",
  "spclties_srch_spclties_and_dept": "ابحث عن التخصصات أو القسم",

  //Doctor list view
  "doc_list_search_doc": "ابحث عن طبيب",
  "doc_list_hsptl_name": "مستشفى الشفاء، الرياض",
  "doc_list_next_available": "أقرب موعد متاح",
  "doc_list_consultation_fee": "رسوم الاستشارة",
  "doc_list_book_hsptl_visit": "احجز زيارة المستشفى",

  //Book Hospital Visit
  "doc_slots_book_hsptl_visit": "احجز زيارة المستشفى",
  "doc_slots_consultation_fee": "رسوم الاستشارة",
  "doc_slots_hsptl_name": "مستشفى الشفاء، الرياض",
  "doc_slots_hsptl_address": "مخرج 14، حي الربوة، الرياض",
  "doc_slots_Schedule": "الجدول",
  "doc_slots_about_doc": "عن الطبيب",
  "doc_slots_reviews": "التقييمات",
  "doc_slots_morning": "الصباح",
  "doc_slots_evening": "المساء",
  "doc_slots_select_slot_to_book_appointment": "اختر وقتًا لحجز الموعد",
  "doc_slots_book_appointment": "احجز موعدًا",

  //About Doctor
  "about_doc_bio": "السيرة الذاتية",
  "about_doc_qualification": "المؤهلات",
  "about_doc_avilability": "التوفر",
  "about_doc_day": "اليوم",
  "about_doc_avilable_hours": "ساعات التوفر",

  //select patient bottomsheet
  "btm_select_patient_txt": "اختر المريض",
  "btm_select_patient_add_member": "إضافة عضو",
  "btm_select_patient_DOB":
      "تاريخ الميلاد", // ❗ not coming due to using the controller
  "btm_select_patient_confirm_patient": "تأكيد المريض",

  //Add family member
  "add_fam_mem_txt": "إضافة أحد أفراد العائلة",
  "add_fam_mem_first_name": "الاسم الأول",
  "add_fam_mem_enter_your_first_name": "أدخل الاسم الأول",
  "add_fam_mem_second_name": "الاسم الثاني",
  "add_fam_mem_enter_your_second_name": "أدخل الاسم الثاني",
  "add_fam_mem_nationality_ID_type": "نوع الهوية الوطنية",
  "add_fam_mem__please_select_a_nationality_ID_type":
      "يرجى اختيار نوع الهوية الوطنية",
  "add_fam_mem_ID_number": "رقم الهوية",
  "add_fam_mem_enter_your_ID_number": "أدخل رقم الهوية",
  "add_fam_mem_dob": "تاريخ الميلاد",
  "add_fam_mem_DD-MM-YYYY": "يوم-شهر-سنة",
  "add_fam_mem_enter_your_dob": "أدخل تاريخ الميلاد",
  "add_fam_mem_select_relation": "اختر",
  "add_fam_mem_relation": "صلة القرابة",
  "add_fam_mem_please_select_a_relation": "يرجى اختيار صلة القرابة",
  "add_fam_mem_add_fam_mem_select_gender": "اختر",
  "add_fam_mem_gender": "الجنس",
  "add_fam_mem_male": "ذكر",
  "add_fam_mem_female": "أنثى",
  "add_fam_mem_please_select_a_gender": "يرجى اختيار الجنس",
  "add_fam_mem_mob_num": "رقم الجوال",
  "add_fam_mem_enter_your_mob_num": "أدخل رقم الجوال",
  "add_fam_mem_cancel": "إلغاء",
  "add_fam_mem_save": "حفظ",
  "add_fam_mem_fam_mem_added_successfully": "تمت إضافة فرد العائلة بنجاح",
  "add_fam_select_gender": "يرجى اختيار الجنس",
  "add_fam_edit_success": "تم تعديل صلة القرابة بنجاح",

  //Review and Pay
  "review_and_pay_txt": "مراجعة ودفع",
  "review_and_pay_appointment_details": "تفاصيل الموعد",
  "review_and_pay_hsptl_name": "مستشفى الشفاء",
  "review_and_pay_hsptl_address": "مخرج 14، حي الربوة، الرياض",
  "review_and_pay_selected_patient": "المريض المختار",
  "review_and_pay_cancel_and_reschudule": "الإلغاء وإعادة الجدولة",
  "review_and_pay_read_cancellation_reschdule_policy":
      "اقرأ سياسة الإلغاء وإعادة الجدولة",
  "review_and_pay_total_bill": "إجمالي الفاتورة",
  "review_and_pay_consultation_fee": "رسوم الاستشارة",
  "review_and_pay_vat": "ضريبة القيمة المضافة",
  "review_and_pay_total_paid": "الإجمالي المدفوع",
  "review_and_pay_pay_txt": "دفع",
  "review_and_pay_confirm_appmnt": "تأكيد الموعد",

  //Cancellation and Reschdule policy = c_r policy
  "c_r_policy_txt": "سياسة الإلغاء وإعادة الجدولة",
  "c_r_policy_cancellation_policy": "سياسة الإلغاء",
  "c_r_cancellation_policy_txt":
      "يُمكن للمرضى الكرام إلغاء المواعيد قبل 24 ساعة من الوقت المحدد من خلال تطبيق الجوال. ونظرًا لكونكم من مرضانا المميزين، سيتم استرداد المبلغ بالكامل في محفظتكم داخل التطبيق، ويمكن استخدامه في الحجوزات المستقبلية. في حال كان الإلغاء بسبب ظروف طارئة، يسعدنا مساعدتكم في إعادة جدولة الموعد في أقرب وقت متاح. نُقدّر بشدة إشعارنا بالإلغاء قبل الموعد بثماني ساعات على الأقل، حيث يتم تخصيص كل موعد بشكل حصري. نلفت عنايتكم إلى أن الإلغاءات المتكررة أو غير الضرورية قد تؤثر على كفاءة جدول المواعيد وتوفر الخدمة للآخرين.",

  "c_r_policy_reschedule_policy": "سياسة إعادة الجدولة",
  "c_r_reschedule_policy_txt":
      "يُتاح للمرضى الكرام إعادة جدولة المواعيد حتى 24 ساعة قبل الموعد الأصلي، وذلك من خلال تطبيق الجوال. وفي حال تعذر الحضور وتم الإلغاء، فسيتم استرداد المبلغ بالكامل في محفظتكم داخل التطبيق كأحد مرضانا المميزين، مع إمكانية استخدامه للحجوزات القادمة. في حال حدوث ظروف طارئة خارجة عن الإرادة، سنبذل قصارى جهدنا لتوفير موعد بديل في أقرب وقت ممكن. نُقدّر إشعارنا المبكر بالإلغاء، لما له من دور في ضمان سير العمل بسلاسة وخدمة جميع المرضى بالشكل الأمثل.",
  "c_r_policy_close": "إغلاق",

  //Bill total
  "bill_total_txt": "إجمالي الفاتورة:",
  "bill_total_hsptl_name": "مستشفى الشفاء، الرياض",
  "bill_total_apply_coupon": "تطبيق كوبون",
  "bill_total_apply": "تطبيق",
  "bill_total_enter_code": "أدخل الرمز",
  "bill_total_total_bill": "إجمالي الفاتورة",
  "bill_total_consultation_fee": "رسوم الاستشارة",
  "bill_total_VAT": "ضريبة القيمة المضافة",
  "bill_total_total_paid": "الإجمالي المدفوع",
  "bill_total_wallet_balance": "رصيد المحفظة: ",
  "bill_total_credit/debit_cards": "بطاقات الائتمان / الخصم",
  "bill_total_add_new_card": "إضافة بطاقة جديدة",
  "bill_total_save_and_pay_via_card": "احفظ وادفع باستخدام البطاقة",
  "bill_total_more_payment_options": "خيارات دفع أخرى",
  "bill_total_pay_at_hospital": "الدفع في المستشفى",
  "bill_total_pay_in_cash_at_hsptl": "الدفع نقدًا أو بالبطاقة في مستشفى الشفاء",
  "bill_total_swipe_to_pay": "اسحب للدفع",
  "bill_total_payment_processing": "جاري معالجة الدفع…",
  "bill_total_coupon_amount": "قيمة القسيمة",

  //Unmatched - requires manual translation or verification
  "booking_confirm_Share": "مشاركة",
  "booking_confirm_hsptl_name": "مستشفى الشفاء، الرياض",
  "booking_confirm_booking_confirmed": "تم تأكيد الحجز",
  "booking_confirm_get_direction": "الحصول على الاتجاهات",
  "booking_confirm_15_min_before_your_slot":
      "يرجى الوصول إلى المستشفى قبل 15 دقيقة من موعدك",
  "booking_confirm_selected_patient": "المريض المختار",
  "booking_confirm_total_bill": "إجمالي الفاتورة",
  "booking_confirm_consultation_fee": "رسوم الاستشارة",
  "booking_confirm_VAT": "ضريبة القيمة المضافة",
  "booking_confirm_total_paid": "الإجمالي المدفوع",
  "booking_confirm_view_appointment": "عرض الموعد",
  "booking_confirm_home": "الرئيسية",

  //wallet balance
  "wallet_txt": "المحفظة",
  "wallet_add_balance": "إضافة رصيد",
  "wallet_your_wallet": "محفظتك",
  "wallet_balance": "الرصيد",
  "wallet_SAR": "ريال سعودي",
  "wallet_transaction_log": "سجل معاملات المحفظة",

  //Add money to wallet
  "money_wallet_txt": "إضافة أموال إلى المحفظة",
  "money_wallet_balance": "رصيد المحفظة",
  "money_wallet_add_money": "أضف أموالاً إلى المحفظة",
  "money_wallet_enter_money": "أدخل مبلغ المحفظة",
  "money_wallet_add": "إضافة المبلغ",
  "money_wallet_added_success": "تمت إضافة المبلغ بنجاح",

//offers list
  "offer_list_txt": "قائمة العروض",
  "offer_valid_date": "العرض ساري",
  "offer_details_txt": "تفاصيل العرض",
  "offer_coupon_code": "رمز الكوبون",
  "offer_copy_coupon_code": "نسخ الرمز",
  "offer_coupon_code_copied": "تم نسخ رمز الكوبون!",
  "offer_valid_upto": "العرض ساري حتى",
  "offer_T_and_C": "الشروط والأحكام",
  "offer_book_now": "احجز الآن",
  "offer_AM": "ص", //doubt
  "offer_pm": "م", //doubt

  //appoinment page = appmnt
  "appmnt_all_patient": "جميع المرضى",
  "appmnt_select_patient": "اختر المريض",
  "appmnt_active_appointments": "المواعيد النشطة",
  "appmnt_hospital_name": "مجمع واحة الشفاء الطبي",
  "appmnt_reschedule": "إعادة الجدولة",
  "appmnt_cancel_appointment": "إلغاء الموعد",
  "appmnt_rate_this_service_now": "قيّم هذه الخدمة الآن",
  "appmnt_cmplt_cncl_appmnt": "المواعيد المكتملة/الملغاة",
  "appmnt_book_flwup_now": "احجز زيارة متابعة",

  //cancel appointment
  "cancel_appmnt_txt": "إلغاء الموعد",
  "cancel_appmnt_r_u_sure_cancel": "هل أنت متأكد من إلغاء الموعد؟",
  "cancel_appmnt_read_policy": "اقرأ سياسة الإلغاء",
  "cancel_appmnt_policy": "سياسة الإلغاء",
  "cancel_appmnt_no": "لا",
  "cancel_appmnt_yes": "نعم",

  //appointment cancelled
  "appmnt_cancled_txt": "تم إلغاء الموعد",
  "appmnt_cancled_successfully": "بنجاح",
  "appmnt_cancled_Close": "إغلاق",

  //Reschedule
  "reschedule_txt": "إعادة جدولة الموعد",
  "reschedule_r_u_sure_cancel": "هل أنت متأكد من إعادة جدولة الموعد؟",
  "reschedule_read_policy": "اقرأ سياسة إعادة الجدولة",
  "reschedule_policy": "سياسة إعادة الجدولة",

  //book follow up
  "book_flw_up_txt": "احجز زيارة متابعة",
  "book_flw_up_appmnt_id": "رقم الموعد",
  "book_flw_up_eligible_flw_up_until": "الزيارة المجانية متاحة حتى:",
  "book_flw_up_txt_book_flw_up_visit": "احجز زيارة المتابعة",

  //star rating
  "rating_rate_this_appmnt": "قيّم هذا الموعد",
  "rating_Helpful": "مفيد",
  "rating_Understanding": "متفهم",
  "rating_Consultation": "الاستشارة",
  "rating_communication": "التواصل",
  "rating_Behaviour": "السلوك",
  "rating_Handling": "التعامل",
  "rating_Write_review": "اكتب تقييمك (اختياري)",
  "rating_submit": "إرسال",
  "rating_close": "إغلاق",

//patient record
  "patient_rec_your_health_record": "سجلك الصحي",
  "patient_rec_dob": "تاريخ الميلاد",
  "patient_rec_gender": "الجنس",

//EMR
  "patient_rec_patient_EMR": "السجل الطبي الإلكتروني",
  "patient_rec_patient_EMR_history": "سجل المريض الإلكتروني",
  "patient_rec_emr_list_all_patient": "جميع المرضى",
  "patient_rec_emr_list_complaint": "الشكوى",
  "patient_rec_emr_list_reports": "التقارير",
  "patient_rec_emr_list_select_patient": "اختر المريض",
  "patient_rec_emr_view_patient_EMR_history": "سجل المريض الإلكتروني",
  "patient_rec_emr_view_dob": "تاريخ الميلاد",
  "patient_rec_emr_view_gender": "الجنس",
  "patient_rec_emr_view_complaint": "الشكوى",
  "patient_rec_emr_view_treatment": "العلاج",
  "patient_rec_emr_view_significant_signs": "الأعراض المهمة",
  "patient_rec_emr_view_vitals": "العلامات الحيوية",
  "patient_rec_emr_view_illness_types": "أنواع الأمراض",
  "patient_rec_emr_view_status": "الحالة",
  "patient_rec_emr_view_diagnosis": "التشخيص",
  "patient_rec_emr_view_view_reports": "عرض التقارير",
  "patient_rec_emr_view_search_mem": "بحث عن عضو",

//Lab report
  "patient_rec_lab_report": "تقرير المختبر",
  "patient_rec_lab_patient_lab_report": "تقرير المختبر للمريض",
  "patient_rec_lab_rep_list_all_patient": "جميع المرضى",
  "patient_rec_lab_rep_list_select_patient": "اختر المريض",
  "patient_rec_lab_rep_list_result_by": "النتيجة بواسطة",
  "patient_rec_lab_rep_list_status": "الحالة",
  "patient_rec_lab_rep_list_reports": "التقارير",
  "patient_rec_lab_rep_view": "عرض تقرير المختبر للمريض",
  "patient_rec_lab_rep_view_order_num": "رقم الطلب",
  "patient_rec_lab_rep_view_payer": "الدافع",
  "patient_rec_lab_rep_view_collection_by": "تم الجمع بواسطة",
  "patient_rec_lab_rep_view_collection_date": "تاريخ الجمع",
  "patient_rec_lab_rep_view_result_by": "تمت النتيجة بواسطة",
  "patient_rec_lab_rep_view_result_date": "تاريخ النتيجة",
  "patient_rec_lab_rep_view_status": "الحالة",
  "patient_rec_lab_rep_view_result_remarks": "ملاحظات النتيجة",
  "patient_rec_lab_rep_view_view_reports": "عرض التقارير",
  "patient_rec_lab_rep_view_search_mem": "بحث عن عضو",

//Procedure Details = proc
  "patient_rec_proc": "الإجراء ",
  "patient_rec_proc_details": "تفاصيل الإجراءات",
  "patient_rec_proc_list_all_patient": "جميع المرضى",
  "patient_rec_proc_list_select_patient": "اختر المريض",
  "patient_rec_proc_list_process_date": "تاريخ الإجراء",
  "patient_rec_proc_list_status": "الحالة",
  "patient_rec_proc_list_reports": "التقارير",
  "patient_rec_proc_view_procedure_details_view": "عرض تفاصيل الإجراء",
  "patient_rec_proc_view_order_num": "رقم الطلب",
  "patient_rec_proc_view_payer": "الدافع",
  "patient_rec_proc_view_item": "العنصر",
  "patient_rec_proc_view_rocess_by": "تم الإجراء بواسطة",
  "patient_rec_proc_view_process_date": "تاريخ الإجراء",
  "patient_rec_proc_view_status": "الحالة",
  "patient_rec_proc_view_remarks": "ملاحظات",
  "patient_rec_proc_view_view_rep": "عرض التقارير",
  "patient_rec_proc_view_search_mem": "بحث عن عضو",

  //Prescription Details = presc
  "patient_rec_presc": "الوصفة الطبية",
  "patient_rec_presc_details": "تفاصيل الوصفة الطبية",
  "patient_rec_presc_list_all_patient": "جميع المرضى",
  "patient_rec_presc_list_select_patient": "اختر المريض",
  "patient_rec_presc_list_name": "الاسم",
  "patient_rec_presc_list_status": "الحالة",
  "patient_rec_presc_list_view_prescription": "عرض الوصفة",
  "patient_rec_presc_details_view": "عرض تفاصيل الوصفة الطبية",
  "patient_rec_presc_view_code": "الرمز",
  "patient_rec_presc_view_payer": "الدافع",
  "patient_rec_presc_view_name": "الاسم",
  "patient_rec_presc_view_gen_name": "الاسم العام",
  "patient_rec_presc_view_order_QTY": "كمية الطلب",
  "patient_rec_presc_view_dispense_QTY": "كمية الصرف",
  "patient_rec_presc_view_status": "الحالة",
  "patient_rec_presc_view_instruction": "التعليمات",
  "patient_rec_presc_view_presc": "عرض الوصفة",
  "patient_rec_presc_view_search_mem": "بحث عن عضو",

  //Radiology = rad
  "patient_rec_rad": "الأشعة",
  "patient_rec_rad_details": "تفاصيل الأشعة",
  "patient_rec_rad_list_all_patient": "جميع المرضى",
  "patient_rec_rad_list_select_patient": "اختر المريض",
  "patient_rec_rad_list_process_date": "تاريخ الإجراء",
  "patient_rec_rad_list_status": "الحالة",
  "patient_rec_rad_list_reports": "التقارير",
  "patient_rec_rad_details_view": "عرض تفاصيل الأشعة",
  "patient_rec_rad_view_order_num": "رقم الطلب",
  "patient_rec_rad_view_payer": "الدافع",
  "patient_rec_rad_view_item": "العنصر",
  "patient_rec_rad_view_process_by": "تم الإجراء بواسطة",
  "patient_rec_rad_view_processdate": "تاريخ الإجراء",
  "patient_rec_rad_view_status": "الحالة",
  "patient_rec_rad_view_remarks": "ملاحظات",
  "patient_rec_rad_view_view_rep": "عرض التقارير",
  "patient_rec_rad_view_search_mem": "بحث عن عضو",

  //sick leave
  "patient_rec_sick_leave": "الإجازة المرضية",
  "patient_rec_sick_leave_letters": "خطابات الإجازة المرضية",
  "patient_rec_sick_list_all_patient": "جميع المرضى",
  "patient_rec_sick_list_select_patient": "اختر المريض",
  "patient_rec_sick_list_created_by": "تم إنشاؤه بواسطة",
  "patient_rec_sick_list_sick_leave_days": "أيام الإجازة المرضية",
  "patient_rec_sick_list_view_letter": "عرض الخطاب",
  "patient_rec_sick_leave_letters_view": "عرض خطاب الإجازة المرضية",
  "patient_rec_sick_view_leave_num": "رقم الإجازة المرضية",
  "patient_rec_sick_view_leave_days": "أيام الإجازة المرضية",
  "patient_rec_sick_view_created_by": "تم إنشاؤه بواسطة",
  "patient_rec_sick_view_remarks": "ملاحظات",
  "patient_rec_sick_view_view_letter": "عرض الخطاب",
  "patient_rec_sick_view_search_mem": "بحث عن عضو",

  //Medical Report = med rep
  "patient_rec_med_rep": "التقرير الطبي",
  "patient_rec_med_rep_list_all_patient": "جميع المرضى",
  "patient_rec_med_rep_list_select_patient": "اختر المريض",
  "patient_rec_med_rep_list_created_by": "تم الإنشاء بواسطة",
  "patient_rec_med_rep_list_rep_num": "رقم التقرير",
  "patient_rec_med_rep_list_reports": "التقارير",
  "patient_rec_med_rep_view": "عرض التقرير الطبي",
  "patient_rec_med_rep_view_med_rep_num": "رقم التقرير الطبي",
  "patient_rec_med_rep_view_created_by": "تم إنشاؤه بواسطة",
  "patient_rec_med_rep_view_remarks": "ملاحظات",
  "patient_rec_med_rep_view_Rep": "عرض التقارير",
  "patient_rec_med_rep_view_search_mem": "بحث عن عضو",

  //Profile page = prof
  "prof_view_acc_details": "عرض تفاصيل الحساب",
  "prof_patient_list": "قائمة المرضى",
  "prof_my_reviews": "تقييماتي",
  "prof_notification_settings": "إعدادات الإشعارات",
  "prof_change_language": "تغيير اللغة",
  "prof_privacy_policy": "سياسة الخصوصية",
  "prof_log_out": "تسجيل الخروج",

//View Account Details
  "prof_acc_details": "تفاصيل الحساب",
  "prof_acc_details_full_name": "الاسم الكامل",
  "prof_acc_details_nationality": "الجنسية",
  "prof_acc_details_nationality_id": "رقم الهوية الوطنية",
  "prof_acc_details_dob": "تاريخ الميلاد",
  "prof_acc_details_gender": "الجنس",
  "prof_acc_details_email": "البريد الإلكتروني",
  "prof_acc_details_prof_pic": "صورة الملف الشخصي",
  "prof_acc_details_log_out": "تسجيل الخروج",

//patient list
  "prof_pati_list_fam_mem": "أفراد العائلة",
  "prof_pati_add_member": "إضافة عضو",

//add family member
  "prof_add_fam_mem_txt": "إضافة عضو",
  "prof_add_fam_mem_fam_mem": "أفراد العائلة",
  "prof_add_fam_mem": "إضافة فرد من العائلة",
  "prof_add_fam_mem_full_name": "الاسم الكامل",
  "prof_add_fam_mem_enter_your_first_name": "أدخل الاسم الأول",
  "prof_add_fam_mem_nationality_ID_type": "نوع الهوية الوطنية",
  "prof_add_fam_mem_please_select_a_nationality_ID_type":
      "يرجى اختيار نوع الهوية الوطنية",
  "prof_add_fam_mem_enter_your_ID_number": "أدخل رقم الهوية",
  "prof_add_fam_mem_ID_number": "رقم الهوية",
  "prof_add_fam_mem_dob": "تاريخ الميلاد",
  "prof_add_fam_mem_enter_your_dob": "أدخل تاريخ الميلاد",
  "prof_add_fam_mem_DD_MM_YYYY": "يوم - شهر - سنة",
  "prof_add_fam_mem_relation": "صلة القرابة",
  "prof_add_fam_mem_select_relation": "اختر",
  "prof_add_fam_mem_please_select_a_relation": "يرجى اختيار صلة القرابة",
  "prof_add_fam_mem_gender": "الجنس",
  "prof_add_fam_mem_please_select_a_gender": "اختر",
  "prof_add_fam_mem_select_gender": "اختر",
  "prof_add_fam_mem_mobile_num": "رقم الجوال",
  "prof_add_fam_mem_enter_your_mobile_num": "أدخل رقم الجوال",
  "prof_add_fam_mem_edit_details": "تعديل التفاصيل",

//my reviews
  "prof_my_review": "التقييمات",

//Notification Settings
  "prof_notification_settings_appbar": "إعدادات الإشعارات",
  "prof_notify_settings_enable_appmnt_reminder": "تفعيل تذكير الموعد",
  "prof_notify_settings_medical_record_update": "تحديث السجل الطبي",
  "prof_notify_settings_health_alerts": "تنبيهات صحية",
  "prof_notify_settings_set_custom_reminder_time": "تحديد وقت مخصص للتذكير",
  "prof_notify_settings_one_day_before": "قبل يوم واحد",
  "prof_notify_settings_save_preference": "حفظ التفضيلات",

//change language
  "prof_chng_lang_set_lang": "تحديد اللغة",
  "prof_chng_lang_arabic_lang": "عربي",
  "prof_chng_lang_english_lang": "الإنجليزية",
  "prof_chng_lang_save_preference": "حفظ التفضيلات",

//Privacy policy
  "prof_privacy_policy_appbar": "سياسة الخصوصية",
  "prof_privacy_policy_txt": "سياسة الخصوصية",
  "prof_terms_and_conditions_txt": "الشروط والأحكام",
  "hsptl_privacy_policy":
      "في مجمع واحة الشفاء الطبي، نحن ملتزمون بحماية خصوصيتك. يتم تخزين جميع المعلومات الشخصية التي يتم جمعها من خلال تطبيقنا، بما في ذلك اسمك ومعلومات الاتصال وسجلاتك الصحية وسجل المواعيد، بشكل آمن ويتم استخدامها فقط للأغراض الطبية والخدمية. نحن نلتزم تمامًا بقوانين حماية البيانات المعمول بها في المملكة العربية السعودية. لن تتم مشاركة بياناتك مع أي طرف ثالث دون موافقتك الصريحة، باستثناء ما يتطلبه القانون أو التنسيق الطبي الضروري. باستخدامك لتطبيقنا، فإنك توافق على جمع واستخدام معلوماتك وفقًا لهذه السياسة. يمكنك تحديث أو طلب إزالة بياناتك في أي وقت من خلال التواصل مع فريق الدعم لدينا.",

//Log out
  "log_out_txt": "تسجيل الخروج",

  "cons_no_data": "لا توجد بيانات لعرضها حاليًا!",
  "cons_no_data_body": "لا توجد بيانات لعرضها حاليًا!",
  "cons_doctor_not_avilable": "الطبيب غير متاح",
  "cons_patient_not_avilable": "المريض غير متاح",
  "somthing_wrng_try_again": "حدث خطأ. يرجى المحاولة مرة أخرى.",

  //
  "registration_num": "رقم التسجيل",
  "reg_age": "العمر",
  "select_options": "اختر من الخيارات",
  "enter_ur_age": "أدخل عمرك",
  "enter_ur_reg_num": "أدخل رقم التسجيل الخاص بك",
  "lang_chnge_success": "Language changed successfully",
  "coupon_success_msg": "تم تغيير اللغة بنجاح",
  "booked_success": "تم الحجز بنجاح",
  "star_rating_success": "تم حفظ التقييم بنجاح",
  "age": "العمر",
  "year": "سنوات",
  "free": "مجاني",
  "added money successfully": "تمت إضافة الأموال بنجاح",
  "rescheduled successfully": "تمت إعادة الجدولة بنجاح",
  "image deleted successfully": "تم حذف الصورة بنجاح",
  "image uploaded successfully!": "تم تحميل الصورة بنجاح!"
};
